language: java
jdk: openjdk11
services:
- docker
before_install:
- docker run -d --name rabbit -p 5672:5672 rabbitmq:3.6
- cat "artifactory_user=${ARTIFACTORY_USERNAME}" >> ~/.gradle/gradle.properties
- cat "artifactory_password=${ARTIFACTORY_PASSWORD}" >> ~/.gradle/gradle.properties
install: true
script:
- |
  if [[ $TRAVIS_COMMIT_MESSAGE != 'SNAPSHOT UPDATE' ]]; then
    ./gradlew build --info;
  fi
env:
  global:
  - SPRING_PROFILES_ACTIVE=default,integration-tests
branches:
  only:
  - master
notifications:
  slack:
    secure: qv9PEK9fWuKJpeTabAvgMM1/I7NO2IsexfpYVNh/ZfbikOku5xAU6KJoepYOByB2Xd5/aLGM8NXmEt5LH19LHSKzNeb5JqoFU2OCkXV93U5WXPV175isUzABfJC7N/ZKb2m9tWc6Rjp+WEEBH736WgrqMGdmELO2VEcEOukSa+IszOGhn5RhQLMLuzrkW2JdmWBVnIHStotGa7By+hxEqRgUNhVaiHj1y7fDtctPjfGklMbETOy6CuqRT7DeGwi0u6PWZs3mIuRzRVfsw/3nuU1axA8+sSEd2z0i8c3nELtZ1RH7Si+D9aQ7TEkVNJFcE2zcpMAi+5QKxoO4xu/RR7XNpIXHZfGl3kotbLtZGkL/kpTs1g6eZAlwOX0WtgyXnnRvH3YxE9ROGaTin9bWBMarFxavHJbMO8qwXrXLRafEPT437GxcNL7UaAdCM/ELRnelDIhnbC1fmeSkHfN9W1wdHWyi8xuaANJtsXVPPmBYDmByU5l7hsLwgyiv7fUDGNfxSXJf7QOZKLEKTYEpea3F6fbWzyKCv6S0MJWM7v7o/pG4T82DKCXWWOfQppFnwe0fNYJmXWGgT1/hmTZzhiPeGm0O83AA6gP5vT+k1zKxKXvvjI6Ohh5aA2BpESkxEhGGCvkzLCeQXo3VeSu4SOgMaPYT/TGc9Emnd4CQjbo=
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
- bash <(curl -s https://codecov.io/bash)
- |
  set -e
  if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ $TRAVIS_COMMIT_MESSAGE != "SNAPSHOT UPDATE" ]]; then
    git config --global user.email "$EMAIL"
    git config --global user.name "$UNAME"
    git checkout master
    num=$(($(grep "version = .*\-SNAPSHOT" build.gradle | sed -e 's/^.*\.\([0-9]*\)-.*$/\1/')+1))
    version=$(grep "version = .*\-SNAPSHOT" build.gradle | sed -E "s/version = '(.+)-SNAPSHOT'/\\1/")
    sed -ie "s/\(^version.*[0-9]*\.[0-9]*\.\)[0-9]*/\1${num}/" build.gradle
    echo $version > concourse_build/version.txt
    git add build.gradle concourse_build/version.txt
    git commit -m "SNAPSHOT UPDATE"
    git push https://$UNAME:$PASSWD@$REPO
  fi
